#!/bin/bash

# Prompt
[ -f /home/yo-lo-pregunto/.config/dotfiles/prompt ] && source /home/yo-lo-pregunto/.config/dotfiles/prompt
# Alias
[ -f /home/yo-lo-pregunto/.config/dotfiles/alias ] && source /home/yo-lo-pregunto/.config/dotfiles/alias

# Fzf
[ -f /home/yo-lo-pregunto/.config/dotfiles/fzf ] && source /home/yo-lo-pregunto/.config/dotfiles/fzf

