#!/bin/bash

# Prompt
[ -f ~/.config/dotfiles/prompt ] && source ~/.config/dotfiles/prompt
# Alias
[ -f ~/.config/dotfiles/alias ] && source ~/.config/dotfiles/alias

# Fzf
[ -f ~/.config/dotfiles/fzf ] && source ~/.config/dotfiles/fzf

