#!/bin/bash

# disable the default virtualenv prompt change
export VIRTUAL_ENV_DISABLE_PROMPT=1

BLUE='\e[0;1;96m'
BLUE_LIGHT='\e[0;38;5;38m'

GREEN='\e[0;38;5;46m'
CYAN='\e[0;38;5;42m'
CYAN_DARK='\e[0;38;5;36m'

GREY='\e[0;37m'

PURPLE='\e[0;38;5;201m'

ORANGE='\e[0;38;5;208m'
ORANGE_BOLD='\e[0;1;38;5;208m'

YELLOW='\e[0;38;5;226m'
YELLOW_BOLD='\e[0;1;33m'

parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/  \1/'
}

function virtualenv_info(){
    # Get Virtual Env
    if [[ -n "$VIRTUAL_ENV" ]]; then
        # Strip out the path and just leave the env name
        venv="${VIRTUAL_ENV##*/}"
    else
        # In case you don't have one activated
        venv=''
    fi
    [[ -n "$venv" ]] && echo " $venv"
}

PS1="\[${GREEN}\]╭[\[${YELLOW_BOLD}\]  \d \[${BLUE}\]󰖉 \A\[${GREEN}\]]\
\[${ORANGE}\]\$(parse_git_branch) \[${CYAN_DARK}\]\$(virtualenv_info)
\[${GREEN}\]╰[\[${YELLOW_BOLD}\] \[${BLUE}\] \W \[${GREEN}\]]\[\e[0m\] "
